server:
  port: 81

#k开启降级feign.hystrix
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false # 消费者不用像eureka注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true