server:
  port: 8002
#mybatis配置
mybatis:
  type-aliases-package: com.wzh.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/DB02?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: Ww123456
    dbcp2:
      test-while-idle: false
#    driver-class-name: com.mysql.jdbc.Driver

#Eureka的配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002


#info配置
info:
  app.name: wzh-springcloud
  company.name: wzh
